### ISSUE TITLE
Eyeliner highlighting the char under cursor as primary

### ISSUE THREAD

**Issue by lourenci** [jinh0/eyeliner.nvim#13]
Thanks for the plugin.

In the print below, the cursor is over `N`. If I call for `eyeliner`, it is considering that `N` under the cursor as the primary one. If you see in the end of the line, there is another `N` that got highlighted as secondary (I use red for primary, black for primary).

<img width="474" alt="image" src="https://user-images.githubusercontent.com/2339362/196300808-c496af6e-659b-4583-8d7e-653eb46caf05.png">

**Comment by jinh0** [comment]
Hey sorry for the really late update! I haven't had the time to work on eyeliner.nvim until just recently.

This was due to an error in the main eyeliner algorithm. I'm currently rewriting the entire plugin in Fennel on the `fnl` branch, where this issue has been fixed! The `fnl` branch should be merged into the `main` branch soon.

**Comment by jinh0** [comment]
Hey @lourenci , this has been fixed on the latest commit . Hope you didn't have to wait too long!

**Comment by lourenci** [comment]
Thank you for that, and for the plugin.

The `main` seems to be broken. The lazy load doesn't work, neither the `highlight_on_key`.

**Comment by jinh0** [comment]
@lourenci  thanks for letting me know that lazy load doesn't work!

I found the culprit and it has been fixed in the latest commit a2c392703ee591e80a962fe907c7d4ba0bdd593b .

Turns out I was stupidly exporting the `enabled` variable as a boolean, which obviously wasn't getting updated after the setup() calls, so I fixed it by exposing `enabled` as a function. 

Lazy load on keypress should work now!

Just as an FYI: eyeliner.nvim doesn't need to be lazy loaded in since it loads in less than 1ms.

**Comment by lourenci** [comment]
Thank you for your quick reply.I just updated it and it is ok now. 👌🏻On 9 Jan 2023, at 11:38 am, Jinho Yoon ***@***.***> wrote:﻿
@lourenci  thanks for letting me know that lazy load doesn't work!
I found the culprit and it has been fixed in the latest commit a2c3927 .
Turns out I was stupidly exporting the enabled variable as a boolean, which obviously wasn't getting updated after the setup() calls, so I fixed it by exposing enabled as a function.
Lazy load on keypress should work now!
Just as an FYI: eyeliner.nvim doesn't need to be lazy loaded in since it loads in less than 1ms.
