### ISSUE TITLE
Use operator-pending mode for `highlight_on_key` instead of hard-coding `d`/`y` mappings

### ISSUE THREAD

**Issue by mawkler** [jinh0/eyeliner.nvim#16]
I noticed that for `highlight_on_key = true` eyeliner hard-codes mappings for `d` and `y` for triggering eyeliner when followed up with `t`/`T`/`f`/`F`. This isn't optimal since there are tonnes of other verbs that aren't covered. For instance `c`, but also any other verb that's not build-in, for instance `ys` from [nvim-surround](https://github.com/kylechui/nvim-surround).

Therefore a better approach is to create an operator-pending eyeliner mapping for `t`/`T`/`f`/`F`. I tried to just add `'o'` to the list of modes to `vim.keymap.set()` [here in `view.lua`](https://github.com/jinh0/eyeliner.nvim/blob/7cf2ddfa9a639b87c40c31818af91581b128634f/lua/eyeliner/view.lua#L44), but sadly that didn't work.

**Comment by williamhCode** [comment]
This also breaks f/t with a number prepending it (e.g., 2f")

**Comment by jinh0** [comment]
Hey everyone, I'm still looking into this issue with operator-pending mode. I'm trying to figure out the best way to do it because, like you mentioned, for some reason it doesn't just work with adding "o".

In the meanwhile, @williamhCode , the number prepending has been fixed in 6a9d0ad714f11cab1691e54e936eaa9881cad277 . :)

**Comment by jinh0** [comment]
Fixed thanks to @TimotheeDesveaux !
