### ISSUE TITLE
Allow option to specify highlight colors

### ISSUE THREAD

**Issue by jinh0** [jinh0/eyeliner.nvim#2]

**Comment by andrewm-brosa** [comment]
+ the option for the colour not to change in combination with bold/underline, so I can keep my existing syntax highlighting while this is active.

**Comment by ggandor** [comment]
Yep, having options in the `setup` is very non-idiomatic. Just expose the highlight groups you use in the code internally.
If one doesn't want to change the colour, just add e.g. underline, they just have to set `:hi EyelinerPrimary gui=underline`. If `nocombine` is not set, it will be "transparent".

**Comment by jinh0** [comment]
> Yep, having highlight options in the setup is very non-idiomatic.

Thanks for letting me know, @ggandor ! 

@andrewferrier , there already exists highlight groups, `EyelinerPrimary` and `EyelinerSecondary`, so as @ggandor mentioned, you can just do `hi EyelinerPrimary gui=underline` that you want. I will add this information to the README so that it is easily accessible.

Right now, if you change the colorscheme, the highlight groups get updated as well. I am working on a fix so that this doesn't happen if somebody specifies a highlight color, like with `hi EyelinerSecondary guifg=#ffffff`.

**Comment by ggandor** [comment]
> so that this doesn't happen if somebody specifies a highlight color

There's no other way than wrapping it in an autocommand:
```vim
autocmd ColorScheme * :hi EyelinerSecondary ...
```
(Technically you could do this instead of the user, i.e., get the currently defined attributes for the Eyeliner highlight groups, and then re-set those inside such an autocommand, but that would be massive overengineering and unnecessary automagic.)

**Comment by ggandor** [comment]
> I guess I'm wondering why it's not idiomatic to put highlight options in the setup function.

Simply because that is an unnecessary abstraction over the conventional mechanism, without any benefit. If you have a `setup` field, you cannot guess the expected value/format - you _have to_ read the documentation. On the other hand, it is enough to list the names of the highlight groups, with their description, you will know what they are for. (In this case these setup fields do not even save us much typing, since we have to provide the exact same kind of highlight definition maps.)

Moreover, if you wrap a native mechanism with your own interface, you sabotage any existing abstractions built on top of that. It is possible that the user, for whatever reason, wants to set a bunch of highlight groups relating to different plugins in one place, e.g., in a function with some convoluted conditional logic. Or maybe they use Fennel, and have elegant macros in their config for wrapping a bunch of `vim.api.nvim_set_hl(...)` calls. You get the point.

**Comment by ggandor** [comment]
Regarding the autocommand, what if the user doesn't want to force the override on _every_ colorscheme change? Generally, highlight group settings tend to depend on the context (i.e., colorscheme, or at least the dark/light background) anyway. It's not the plugin's job to "resurrect" the user's custom group definitions, no plugin does this.

**Comment by jinh0** [comment]
Oh that makes a lot of sense. Thank you for taking the time to write up the explanation!

I will add the autocmd information to the documentation. Other than that, I think this issue can be closed.
