### ISSUE TITLE
Multiple unique characters?

### ISSUE THREAD

**Issue by ghostbuster91** [jinh0/eyeliner.nvim#20]
Hi, first thanks for the great plugin.

I am using following version: `353e7b2f517953c48608ee158ebd161ca5b6cfae`

Below a gif showing my problem:
![eyeliner](https://user-images.githubusercontent.com/5662622/210418122-cafb01cc-b270-4f9a-be6e-fdf38df9a1fc.gif)

For some reason eyeliner highlights multiple a's even though they are not unique. Any idea what could be wrong?

**Comment by jinh0** [comment]
Hey @ghostbuster91 thanks for the issue. This is because the current eyeliner algorithm considers numbers as delimiters for new words, i.e., it thinks that that one long string of numbers and letters is a bunch of words separated by numbers.

I've fixed this in the `fnl` branch, I'll keep you updated when I push this to `main`.

**Comment by jinh0** [comment]
Hey @ghostbuster91 it's fixed on `main` by this commit 92954801298ec16f004c7d3b1b86d90c0e7c6bf5 .

Let me know if it works, and then I'll close this issue!

**Comment by ghostbuster91** [comment]
Thanks @jinh0 !
