### ISSUE TITLE
Expose `handle_key` for external use 

### ISSUE THREAD

**Issue by ghostbuster91** [jinh0/eyeliner.nvim#23]
Hi, I started to develop a new plugin to dispatch `;` into a wide variety of custom repeatable motions. https://github.com/ghostbuster91/nvim-next It is still super early version but I would like to integrate it with your plugin since I am using eyeliner in my setup. 

Could you expose `handle_key` method so I would be able to wire it into my plugin?

**Comment by jinh0** [comment]
Hey @ghostbuster91 , I just exposed the method on the latest commit. 

You can access the function by `require("eyeliner.on-key").handle_keypress(key)`. In my own testing, running this function outside of eyeliner's normal workflow doesn't do anything, I don't know quite why. Maybe it'll work for you?

In general, I know there are some issues when you have multiple plugins like eyeliner and clever-f at the same time since they override the same keys, so I am interested in allowing users to use the handle_keypress function freely.

A solution might be allowing hooks for the keypress event, like
```lua
require"eyeliner".setup {
    before_highlight = function()
        -- some code you want to run before highlighting
    end,
    after_highlight = function()
        -- some code you want to run after
    end,
}
```

I am interested in adding clever-f functionality into eyeliner, as mentioned in #11 .

Let me know what you think!

**Comment by ghostbuster91** [comment]
Hi thanks, 
I've just tested it in the following setup but it doesn't work for me either. 
```lua
local eyeliner = require("eyeliner.on-key").handle_keypress
local next = require("nvim-next").setup({
    default_mappings = {
        repeat_style = "directional",
    },
})
map({ "n", "x" }, "f", next.make_repeatable_pair(eyeliner("F"), eyeliner("f")), { noremap = true })
map({ "n", "x" }, "F", next.make_repeatable_pair(eyeliner("f"), eyeliner("F")), { noremap = true })
map({ "n", "x" }, "t", next.make_repeatable_pair(eyeliner("T"), eyeliner("t")), { noremap = true })
map({ "n", "x" }, "T", next.make_repeatable_pair(eyeliner("t"), eyeliner("T")), { noremap = true })
```

**Comment by edte** [comment]
Hello, when I execute `require("eyeliner.on-key").handle_keypress("f")`, an error will be reported.

```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'handle_keypress' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

**Comment by jinh0** [comment]
Hi @edte and @ghostbuster91  , I've finally gotten around to adding this functionality. You can now use `require("eyeliner").highlight({ forward = true })`. I've added more information in the [README](https://github.com/jinh0/eyeliner.nvim?tab=readme-ov-file#advanced-configuration) .

Thanks for the feature suggestion! Let me know if there are any problems, I'll reopen the issue!
